name: publish
on:
  push:
    branches:
      - main
      - dev
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: run
        id: main
        run: |
          pip install --no-color --progress-bar=off --editable ".[dev]"
      - name: tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.main.outputs.tag}}',
              sha: context.sha
            })
